name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: EducationGood2023!!
          MYSQL_DATABASE: gambling
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, pdo_mysql
        coverage: xdebug

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: gambling
        DB_USERNAME: peroxideDB
        DB_PASSWORD: EducationGood2023!!
      run: php artisan test
